### ISSUE TITLE
Unable to view/edit forms saved recently

### ISSUE THREAD

**Issue by jedweb** [xybal/EventBookingProJqueryFix#1]
I'm unable to view forms I saved recently. I can view previously created forms but if I edit one of them and then save it, trying to edit it again doesn't work. No fields are displayed. 

This is the error I get from the console:

/wp-admin/admin.php?…tManagementForms#:1 

Uncaught SyntaxError: Unexpected string in JSON at position 3
    at JSON.parse (<anonymous>)
    at Object.getLanguagedText (adminHelper.js:83)
    at Object.getField (adminHelper.js:206)
    at Object.getFormEditSection (adminHelper.js:373)
    at getFormEditsSection (admin.js:107)
    at Object.success (admin.js:100)
    at i (jquery-1.12.4-wp.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.12.4-wp.js:2)
    at x (jquery-1.12.4-wp.js:4)
    at XMLHttpRequest.c (jquery-1.12.4-wp.js:4)

**Comment by jedweb** [comment]
I can't view any of the forms now.

VM2381:1 Uncaught SyntaxError: Unexpected string in JSON at position 3
    at JSON.parse (<anonymous>)
    at Object.getLanguagedText (adminHelper.js?ver=5.7:83)
    at Object.getField (adminHelper.js?ver=5.7:206)
    at Object.getFormEditSection (adminHelper.js?ver=5.7:373)
    at getFormEditsSection (admin.js?ver=5.7:107)
    at Object.success (admin.js?ver=5.7:100)
    at i (jquery-1.12.4-wp.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery-1.12.4-wp.js?ver=1.12.4-wp:2)
    at x (jquery-1.12.4-wp.js?ver=1.12.4-wp:4)
    at XMLHttpRequest.c (jquery-1.12.4-wp.js?ver=1.12.4-wp:4)

**Comment by xybal** [comment]
Have you changed the adminHelper.js content back to te txt file I sent you on the previous message ?

**Comment by jedweb** [comment]
Yes, I changed it back. Was that the original source in that file? I made a backup before I made the first change.

I thought I couldn't view any forms but I'm actually able to vew a few of my forms.

**Comment by xybal** [comment]
Yes it was the original source in that file. Any idea of what type of fields are inside the defective forms ?

**Comment by jedweb** [comment]
The forms have name field, email field, text fields, a few checkboxes, a
radio button field, 3 ticket types to choose from and a static field.

**Comment by xybal** [comment]
I just tried to make the same form (when you refer to ticket types, are they select fields ? ) and everything is working in my case. The error is still the one you posted 5 days ago ?

**Comment by jedweb** [comment]
The registration forms I have for the two courses on the following page
were made by duplicating old forms. After I duplicated them, edited them,
and then saved the changes, I am no longer able to view/edit them in the
back end.

https://orthodivontario.ca/courses/

Jim

**Comment by xybal** [comment]
Jim, thanks to let me access your form it's the double quote character that is causing the mess. Change the adminHelper.js content with the one here it should solve the issue. Let me know :)
[adminHelper.txt](https://github.com/xybal/EventBookingProJqueryFix/files/6192607/adminHelper.txt)

**Comment by jedweb** [comment]
Thanks. I tried the new code but unfortunately I still can't view the ones I've saved recently. Here's the error:

Uncaught SyntaxError: Unexpected token z in JSON at position 100
    at JSON.parse (<anonymous>)
    at Object.getLanguagedText (adminHelper.js?ver=5.7:83)
    at Object.getInputField (adminHelper.js?ver=5.7:149)
    at Object.getField (adminHelper.js?ver=5.7:242)
    at Object.getFormEditSection (adminHelper.js?ver=5.7:373)
    at getFormEditsSection (admin.js?ver=5.7:107)
    at Object.success (admin.js?ver=5.7:100)
    at i (jquery-1.12.4-wp.js?ver=1.12.4-wp:2)
    at Object.fireWith [as resolveWith] (jquery-1.12.4-wp.js?ver=1.12.4-wp:2)
    at x (jquery-1.12.4-wp.js?ver=1.12.4-wp:4)

**Comment by xybal** [comment]
Are you sure you changed correctly the content of the adminHelper.js file ? You are giving me an error at a line that isn't corresponding with the changed I made yesterday. Have you cleared your browser cache (and server one if you are using a cache plugin / settings) ?

**Comment by jedweb** [comment]
Yeah, it was a caching issue. I did a hard refresh but I didn't specifically clear cache. The forms are displaying now. 

Thanks!!

**Comment by xybal** [comment]
Glad it helped :)
